# -*- coding: utf-8 -*-
"""TGCA-ESCA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AusfpX320DKHfEoVkl2qL0BMODi5JChx

The miRNA expression data should be in Transcriptome_Profiling/miRNA_Expression_Quantification/ in the working directory.
Clinical_to_Seq_Data.csv correlates the clinical data to expression data.
clinical.csv in Clinical subfolder has the disease labels for the patients.
Final data should be in two folders in the working directory:(Esophagus Adenocarcinoma, NOS) and (Esophagus Squamous Cell Carcinoma) according to the disease state.
Each file in the folders represents a patient. The file name is the case ID of that patient. Each file has the miRNA counts for that patient.
"""

#from google.colab import drive
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from numpy.lib.function_base import cov
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
import math
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import KFold
import itertools

def PCA_visualize(samples,labels):
  ##samples = data array (shape = num_patients, num_miRNAs)
  samples = np.array(samples)
  samples = samples.T
  labels = np.array(labels)

  ##standardize data since PCA is sensitive to scale
  scaler = StandardScaler()
  samples = scaler.fit_transform(samples)

  ##covariance matrix of features (i.e. normalized miRNA counts)
  cov_mat = np.cov(samples)
  print(samples.shape)
  print(cov_mat.shape)

  ##fit the original data
  eig_val, eig_vec = np.linalg.eig(cov_mat)
  order_eig_val = np.argsort(eig_val)

  ##find top 2 principle components
  ordered_eig_val = eig_val[order_eig_val]
  ordered_eig_vec = eig_vec[:,order_eig_val]
  eig_val = ordered_eig_val[-2:]
  total_var = np.sum(ordered_eig_val).real
  print("Total Variance: ", total_var)
  print("Variance explained by PC1 and PC2: ", np.sum(eig_val).real*100/total_var)
  eig_vec = ordered_eig_vec[:,-2:]

  ##project the original data to a top two principal components
  pca_X = np.dot(samples.T,eig_vec)
  plot = plt.scatter(pca_X[:,0], pca_X[:,1], c=labels)
  plt.title("PCA Visualization of Data")
  plt.xlabel("PC1")
  plt.ylabel("PC2")
  plt.legend(handles=plot.legend_elements()[0], labels=['Adenocarcinoma','Squamous Cell Carcinoma'])
  plt.show()

def get_accuracy_score(y_test, y_pred):
  return accuracy_score(y_test, y_pred)

def get_F1_score(y_test, y_pred):
  return f1_score(y_test, y_pred)

def get_confusion_matrix(y_test, y_pred):
  return confusion_matrix(y_test, y_pred)

def plot_confusion_matrix(predicted_labels_list, y_test_list):
    cnf_matrix = confusion_matrix(y_test_list, predicted_labels_list)
    np.set_printoptions(precision=2)

    plt.figure()
    class_names = ['Adenocarcinoma','Squamous Cell Carcinoma']

    # Plot normalized confusion matrix
    plt.figure()
    generate_confusion_matrix(cnf_matrix, classes=class_names, normalize=True, title='Confusion Matrix')
    plt.show()

def generate_confusion_matrix(cnf_matrix, classes, normalize=False, title='Confusion matrix'):
    if normalize:
        cnf_matrix = cnf_matrix.astype('float') / cnf_matrix.sum(axis=1)[:, np.newaxis]
        print("Normalized confusion matrix")
    else:
        print('Confusion matrix, without normalization')

    plt.imshow(cnf_matrix, interpolation='nearest', cmap=plt.get_cmap('Blues'))
    plt.title(title)
    plt.colorbar()

    tick_marks = np.arange(len(classes))
    plt.xticks(tick_marks, classes, rotation=45)
    plt.yticks(tick_marks, classes)

    fmt = '.2f' if normalize else 'd'
    thresh = cnf_matrix.max() / 2.

    for i, j in itertools.product(range(cnf_matrix.shape[0]), range(cnf_matrix.shape[1])):
        plt.text(j, i, format(cnf_matrix[i, j], fmt), horizontalalignment="center",
                 color="white" if cnf_matrix[i, j] > thresh else "black")

    plt.tight_layout()
    plt.ylabel('True label')
    plt.xlabel('Predicted label')

    return cnf_matrix


def evaluate_SVC(data_x, data_y):
    k_fold = KFold(10, shuffle=True, random_state=1)

    predicted_targets = np.array([])
    actual_targets = np.array([])

    for train_ix, test_ix in k_fold.split(data_x):
        train_x, train_y, test_x, test_y = data_x[train_ix], data_y[train_ix], data_x[test_ix], data_y[test_ix]

        # Fit the classifier
        classifier = svm.SVC().fit(train_x, train_y)
        # Predict the labels of the test set samples
        predicted_labels = classifier.predict(test_x)

        predicted_targets = np.append(predicted_targets, predicted_labels)
        actual_targets = np.append(actual_targets, test_y)
    accuracy = cross_val_score(classifier, data_x, data_y, scoring='accuracy', cv = 10)
    print("Mean Accuracy for 10-fold cross validation: ", accuracy.mean()*100)
    f1 = cross_val_score(classifier, data_x, data_y, scoring='f1', cv = 10)
    print("Mean F1-score for 10-fold cross validation: ",f1.mean())

    return predicted_targets, actual_targets

def evaluate_RandomForest(data_x, data_y):
    k_fold = KFold(10, shuffle=True, random_state=1)

    predicted_targets = np.array([])
    actual_targets = np.array([])

    for train_ix, test_ix in k_fold.split(data_x):
        train_x, train_y, test_x, test_y = data_x[train_ix], data_y[train_ix], data_x[test_ix], data_y[test_ix]

        # Fit the classifier
        classifier = RandomForestClassifier(max_depth=2, random_state=0).fit(train_x, train_y)
        # Predict the labels of the test set samples
        predicted_labels = classifier.predict(test_x)

        predicted_targets = np.append(predicted_targets, predicted_labels)
        actual_targets = np.append(actual_targets, test_y)
    accuracy = cross_val_score(classifier, data_x, data_y, scoring='accuracy', cv = 10)
    print("Mean Accuracy for 10-fold cross validation: ", accuracy.mean()*100)
    f1 = cross_val_score(classifier, data_x, data_y, scoring='f1', cv = 10)
    print("Mean F1-score for 10-fold cross validation: ",f1.mean())

    return predicted_targets, actual_targets

class LogisticRegression:
    def __init__(self, d):
        self.w = np.random.randn(d)

    def compute_grad(self, X, Y):
        """
        Compute the derivative of l(w).
        Inputs: Same as above.
        Returns:
            A numpy array of size (d,).
        """
        gradient = np.zeros_like(self.w)
        d = self.w.size
        n = Y.size

        for j in range(d):
            avg_term = 0.0
            sum_of_terms = 0.0
            for i in range(n):
                e_term = pow(math.e,np.matmul(self.w,X[i]))
                frac_term = 1/(1 + e_term)
                term = frac_term * e_term * X[i][j] - Y[i]* X[i][j]
                sum_of_terms += term
            avg_term = sum_of_terms/n
            gradient[j] = avg_term

        return gradient

    def fit(self, X, Y):
        """
        Train the model with gradient descent.
        Update self.w with the algorithm listed in the problem.
        Returns: Nothing.
        """
        some_i = 0
        while some_i<=100:
            some_i += 1
            if some_i%20==0:
              print(some_i)
            gradient = self.compute_grad(X,Y)
            some_sum = 0.0
            for wj in gradient:
                some_sum += wj*wj
            magnitude_of_gradient = math.sqrt(some_sum)
            for j in range(gradient.size):
                self.w[j] -= gradient[j]

def find_prob_label(prod):
  prob0 = 1/(1+math.exp(prod))
  prob1 = 1-prob0
  if prob1 > prob0:
    return 1
  else:
    return 0

def find_prob_label_mul_samples(test_data_r,w):
  all_labels = []
  for sample in test_data_r:
    prod = np.matmul(sample,w)
    pred_label = find_prob_label(prod)
    all_labels.append(pred_label)
  return all_labels

def evaluate_LogReg(data_x, data_y):
    k_fold = KFold(10, shuffle=True, random_state=1)

    predicted_targets = np.array([])
    actual_targets = np.array([])
    accuracy = []
    f1_score = []
    for train_ix, test_ix in k_fold.split(data_x):
        train_x, train_y, test_x, test_y = data_x[train_ix], data_y[train_ix], data_x[test_ix], data_y[test_ix]

        # Fit the classifier

        classifier = LogisticRegression(train_x.shape[1])
        classifier.fit(train_x, train_y)

        # Predict the labels of the test set samples
        predicted_labels = find_prob_label_mul_samples(test_x,classifier.w)

        predicted_targets = np.append(predicted_targets, predicted_labels)
        actual_targets = np.append(actual_targets, test_y)

        accuracy.append(get_accuracy_score(test_y, predicted_labels))
        f1_score.append(get_F1_score(test_y,predicted_labels))

    print("Mean Accuracy for 10-fold cross validation: ",np.array(accuracy).mean()*100)
    print("Mean F1-score for 10-fold cross validation: ",np.array(f1_score).mean())


    return predicted_targets, actual_targets


#drive.mount('/content/drive')
# %cd /content/drive/MyDrive/TCGA-ESCA/harmonized/
if __name__ == '__main__':
    clinical_dict = {}
    data_dict = {}

    file_to_case = pd.read_csv("Clinical_to_Seq_Data.csv", sep=',',index_col=0)
    file_to_case = file_to_case.set_index('filename')
    file_to_case_dict = file_to_case.T.to_dict('list')

    for folder in os.listdir("Transcriptome_Profiling/miRNA_Expression_Quantification/"):
      for file in os.listdir("Transcriptome_Profiling/miRNA_Expression_Quantification/"+folder):
        file_path = os.path.join("Transcriptome_Profiling/miRNA_Expression_Quantification/"+folder, file)
        data=pd.read_csv(file_path, sep='\t')
        case_ID = file_to_case_dict[file][0][:12]
        data_dict[case_ID] = data


    for file in os.listdir("Clinical/"):
      if ".csv" not in file:
        continue
      data=pd.read_csv("Clinical/"+file, sep=',')
      for i in range(len(data)):
        clinical_dict[data.bcr_patient_barcode[i]] = data.primary_pathology_histological_type[i]

    for patient in data_dict:
      disease_type = clinical_dict[patient]
      data = data_dict[patient]
      data.to_csv(disease_type+"/"+patient+".csv")

    """Data in for of array (num_patients x num_miRNAs), y - 0 or 1 depending on cancer subtype"""
    samples = []
    labels = []
    for file in os.listdir("Esophagus Adenocarcinoma, NOS/"):
      df = pd.read_csv("Esophagus Adenocarcinoma, NOS/"+file)
      sample = np.array(df['reads_per_million_miRNA_mapped'])
      samples.append(sample)
      labels.append(0)
    for file in os.listdir("Esophagus Squamous Cell Carcinoma/"):
      df = pd.read_csv("Esophagus Squamous Cell Carcinoma/"+file)
      sample = np.array(df['reads_per_million_miRNA_mapped'])
      samples.append(sample)
      labels.append(1)


    PCA_visualize(samples,labels)

    samples_np = np.asarray(samples) #convert to numpy array
    labels_np = np.asarray(labels) #convert to numpy array

    """
    Train test split of samples_np and labels_np. Only use the train data from the fit for each evaluate_model and confusion matrix
    Then use test data to find final test accuracy, F1 score and confusion matricx for each model.
    Standardize after train-test split
    """
    X_train, X_test, y_train, y_test = train_test_split(samples_np, labels_np, test_size=0.2, random_state=42)
    scaler = StandardScaler()
    X_train_std = scaler.fit_transform(X_train)
    X_test_std = scaler.fit_transform(X_test)

    """10-fold cross-validation of SVM Classifier"""
    predicted_target, actual_target = evaluate_SVC(X_train_std, y_train)
    plot_confusion_matrix(predicted_target, actual_target)


    """10-fold cross-validation of Ranom Forest Classifier"""
    predicted_target, actual_target = evaluate_RandomForest(X_train_std, y_train)
    plot_confusion_matrix(predicted_target, actual_target)

    """
    Logistic Regression
    Without B0 regression coefficient considered
    Add the constant term to the data to eliminate B0 coefficient, then standardize.
    """
    X_train_with_1 = np.insert(X_train, 0, 1, axis=1)
    X_train_with_1_standard = scaler.fit_transform(X_train_with_1)

    X_test_with_1 = np.insert(X_test, 0, 1, axis=1)
    X_test_with_1_standard = scaler.fit_transform(X_test_with_1)


    """10-fold cross-validation of Logistic Regression"""
    predicted_target, actual_target = evaluate_LogReg(X_train_with_1_standard, y_train)
    plot_confusion_matrix(predicted_target, actual_target)

    """Test Accuracy for each model"""
    classifier = svm.SVC().fit(X_train_std, y_train)
    # Predict the labels of the test set samples
    predicted_labels = classifier.predict(X_test_std)
    print("Test Accuracy for SVM Classifier: ",get_accuracy_score(y_test, predicted_labels)*100)
    print("F1-score for SVM Classifier: ",get_F1_score(y_test,predicted_labels))

    classifier = RandomForestClassifier(max_depth=2, random_state=0).fit(X_train_std, y_train)
    # Predict the labels of the test set samples
    predicted_labels = classifier.predict(X_test_std)
    print("Test Accuracy for Random Forest Classifier: ",get_accuracy_score(y_test, predicted_labels)*100)
    print("F1-score for Random Forest Classifier: ",get_F1_score(y_test,predicted_labels))

    classifier = LogisticRegression(X_train_with_1_standard.shape[1])
    classifier.fit(X_train_with_1_standard, y_train)
    # Predict the labels of the test set samples
    predicted_labels = find_prob_label_mul_samples(X_test_with_1_standard,classifier.w)
    print("Test Accuracy for Logistic Regression: ",get_accuracy_score(y_test, predicted_labels)*100)
    print("F1-score for Random Logistic Regression: ",get_F1_score(y_test,predicted_labels))
